---
title: "Instacart Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    navbar:
      - { title: "Home", href: index.html, align:left}
---

```{r setup, include=FALSE}
library(flexdashboard)
library(p8105.datasets)
library(plotly)
library(dplyr)

```

Column {data-width=650}
-----------------------------------------------------------------------
### Re-order Behavior in the Week

```{r}
# randomly select 2000 samples
instacart_data = instacart |>
  janitor::clean_names() |>
  sample_n(2000) 


```

```{r}
plot_ly(data = instacart_data, x = ~order_dow, y = ~order_hour_of_day, type = "scatter", mode = "markers", color = ~reordered) |>
  layout(title = "Order Day of Week vs. Hour of Day",
         xaxis = list(title = "Order Day of Week",
                      tickvals = c(0, 1, 2, 3, 4, 5, 6),
                      ticktext = c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday")),
         yaxis = list(title = "Order Hour of Day"))


```

Column {data-width=650}
-----------------------------------------------------------------------

### Customer Order Number by Department

```{r}
# order number by department
plot_ly(data = instacart_data, y = ~order_number, type = "box", color = ~department, colors = "viridis") |>
  layout(title = "Customer Order Number by Department",
         yaxis = list(title = "Order Number"))

```

### Re-order Rate by Department

```{r}

# re-order rate by department
reorder_rate = instacart_data |>
  group_by(department) |>
  summarise(reorder_rate = mean(reordered))

plot_ly(data = reorder_rate, x = ~department, y = ~reorder_rate, color = ~department, type = "bar",colors = "viridis") |>
  layout(title = "Reorder Rate by Department",
         xaxis = list(title = "Department"),
         yaxis = list(title = "Reorder Rate"))


```








